sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
before_install:
  - git fetch --depth=1 origin master:master
script:
  - yarn lint
  - yarn lint:css
  - yarn test:ci
  - yarn build
  - yarn catalog-build
after_success:
  - npx codecov
deploy:
  # deploy catalog from master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: catalog/build
    target-branch: gh-pages
    on:
      branch: master
  # trigger latest release from master branch
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
  # trigger beta release from beta branch
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release@beta
    on:
      branch: beta
branches:
  only:
    - master
    - beta
    - /^greenkeeper/.*$/
