sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run lint
  - npm run test:cover
  - npm run build
  - npm run catalog-build
after_success:
  - npx codecov
  - npx gh-pages -d catalog/build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
