sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run lint
  - npm run lint:css
  - npm run test:cover
  - npm run build
  - npm run catalog-build
after_success:
  - npx codecov
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: catalog/build
    target-branch: gh-pages
    on:
      branch: master
branches:
  only:
    - master
    - /^greenkeeper/.*$/
